@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "Airport_Manager"
participant "System" as Sys
activate Airport_Manager

Airport_Manager -> Sys: Enters receptionist data
Airport_Manager -> Sys: Saves data
Sys --> Sys: Validates data

 group "alt" Data Valid
    alt Data Valid
        Sys -> Sys: Stores receptionist data
        Sys --> Airport_Manager: Returns Success
    else Data Invalid
        Sys --> Airport_Manager: Returns Failure
 end

@enduml