@startuml

autoactivate on
autonumber


participant "controller: Controller" as Ctrl
participant "view: View" as View
participant "mainManagerView: MainManagerView" as MainManagerView
participant ":Utils" as Utils
participant "airportManager: AirportManager" as AirportManager
participant "model: Airport" as Airport
participant "airportManagerContainer: AirportManagerContainer" as Container


Ctrl -> View: menuAirport
View --> Ctrl
Ctrl -> View: menuMainManager
View --> Ctrl

Ctrl -> MainManagerView: getAirportManager
MainManagerView -> MainManagerView: getManagerID
MainManagerView -> Utils: getString()
Utils --> MainManagerView: name
MainManagerView -> Utils: getString()
Utils --> MainManagerView: loginInfo
MainManagerView -> AirportManager**: <<create>>
MainManagerView --> Ctrl: airportManager

Ctrl -> Airport: getAirportManagerContainer
Airport --> Ctrl: airportManagerContainer

Ctrl -> Container: add(airportManager)
Container --> Ctrl

@enduml