@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "Main_Manager"
participant "System" as Sys
activate Main_Manager

Main_Manager -> Sys: Enters flight manager data
Main_Manager -> Sys: Saves flight manager data
Sys --> Sys: Validates data

 group "alt" Data Valid
    alt Data Valid
        Sys -> Sys: Stores flight manager data
        Sys --> Main_Manager: Returns Success
    else Data Invalid
        Sys --> Main_Manager: Returns Failure
 end

@enduml