@startuml
skinparam classAttributeIconSize 0
hide circles

class comp1 {

}

class comp2 {

}

comp1 --* comp2
comp1 -0)- comp2
comp1 --o comp2
comp1 --^ comp2
comp1 --> comp2
comp1 ..> comp2

' *-- = agregações ; relações mais fortes ;
'       ja não pode/deve existir sem a outra
'       (comp1 precisa de comp2)

' --o = agregações ; relações mais fracas ;
'       mais independentes ; podem existir sem essa parte
'       comp1 pode existir sem comp2

' --^ = herança (comp1 herda de comp2)

' ..> = dependencia ; uso algo da outra class ;
'       quando uso #include (comp1 depende de comp2)

@enduml

